### ISSUE TITLE
How to deal with large videos

### ISSUE THREAD

**Issue by benemana** [gkordo/s2vs#4]
Hi Giorgos,
thanks again for this work and for your support in my previous issues.

After some experiments on custom videos, I'm struggling with calculating the similarity between large videos (>7 min), due to a limted amount of memory in my GPU.

In fact, when I try to process such videos, I get a _"CUDA out of memory error"_.

I managed to overcome this issue in the features extraction part, by setting fps=1 and splitting the query and target videos into N chuncks, computing the features for each chunck and then stack together all the N features tensor into a single features tensor (does it make sense?).

But when it comes to the similarity part, specifically with the `calculate_video_similarity` function, I get the above error.

Do you have any suggestion on how to optimize the similarity part for such videos?
 
I guess that splitting the query and target videos into several chuncks and compute the similarity between chunks would not result in a meaningful similarity check, but maybe I'm wrong.

Thanks a lot.

EDIT: After further investigation, it seems that what is causing the error is the `torch.einsum` operation inside the `frame_to_frame_similarity` function.

**Comment by benemana** [comment]
After further investigation, it seems that what is causing the error is the `torch.einsum` operation inside the `frame_to_frame_similarity` function.

**Comment by gkordo** [comment]
hi @benemana. Apologies for the late reply; I missed your issue.
I had solved this issue using baching on the target side (have a look here [here](https://github.com/gkordo/s2vs/blob/03eb0c9a9a7455d132c4210b797fa6ef563b52ea/evaluation.py#L25)).

In essence, you can split the feature tensors of your query and target videos into batches/parts of features and process them independently. Also, you can use baching on both the query and target sides. Following is an example of how to do this: 
```python
import utils
import torch

torch.set_grad_enabled(False) # disable gradient computation

model = torch.hub.load('gkordo/s2vs:main', 's2vs_dns').cuda().eval()

# two large feature tensors of the query and target videos
query = torch.rand(1000, 9, 512)
target = torch.rand(10000, 9, 512)
batch_sz = 100

similarities = []
for qbatch in utils.batching(query, batch_sz): # baching on query side
    sim = []
    for tbatch in utils.batching(target, batch_sz): # baching on target side
        sim.append(model.calculate_video_similarity(qbatch.cuda(), tbatch.cuda())) # compute similarity between the two batches
    similarities.append(torch.cat(sim, 1))
similarities = torch.cat(similarities, 0)
```

Now, you can use various approaches to aggregate the similarities between batches, such as mean, max, or Chanfer similarity. You can do as follows:
```python
similarities = similarities.mean()
# or
similarities = similarities.max()
# or
similarities = torch.max(similarities, 1)[0].mean()
```

Please let me know if you need something else, and I will try to reply earlier next time :)

**Comment by gkordo** [comment]
I am closing the issue due to inactivity. Feel free to re-open it.
